### ISSUE TITLE
Home - Revisão de Proposta de Design

### ISSUE THREAD

**Issue by alexgwasp** [TransEmpregos/transempregos-portal#38]
O Bruno e a Thuany irão rever a home do site e propor um novo layout para a parte das "abas", nesse campo deveria estar clara a idéia de botões mas todos entenderam que se tratavam de abas.

*O novo layout deve ser entregue o quanto antes para codificação do time de Dev.

**Comment by brunorani** [comment]
@alexgwasp Segue o layout revisado da Home para readaptação. 
![transempregos_home_revisao](https://cloud.githubusercontent.com/assets/20519466/22341567/6c400630-e3d8-11e6-9aa2-06bbd110375d.jpg)

**Comment by alexgwasp** [comment]
Faltou só:
- Colocar negrito nos textos do header e nos botões
- Retirar espaço em branco no final da página

**Comment by giggio** [comment]
Closed on #53
