### ISSUE TITLE
Bug - Tela Cadastro de Vaga

### ISSUE THREAD

**Issue by alexgwasp** [TransEmpregos/transempregos-portal#61]
Na tela de cadastro de vagas, quando eu salvo uma vaga e ele retorna para a tela de listagem de vagas as outras vagas já cadastradas não aparecem. Se você der um refresh na página as vagas aparecerão. Tela: http://transempregos-dev.azurewebsites.net/admin/job

* Ver se o refresh está acontecendo quando o usuário volta para a lista de vagas após ter salvado uma vaga nova.

**Comment by ansusambu** [comment]
@giggio preciso de ajuda com refresh  nos requests.
